env:
  browser: true
  es2021: true
  node: true
  jest: true
  mocha: true
extends: ['eslint:recommended', 'google']
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  "no-invalid-this": 0
}

